// <auto-generated />
using System;
using CheapNights.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CheapNights.Migrations
{
    [DbContext(typeof(CheapNightsDbContext))]
    [Migration("20260409201303_AddCalendarToken")]
    partial class AddCalendarToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CheapNights.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("CalendarToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlexUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarToken")
                        .IsUnique()
                        .HasFilter("\"CalendarToken\" IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("CheapNights.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeColor")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CheapNights.Models.EntryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EntryTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Game",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movie",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "DLC",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("CheapNights.Models.GameEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedTime")
                        .HasColumnType("text");

                    b.Property<int>("EntryTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("GameNote")
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCouchCoop")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMovie")
                        .HasColumnType("boolean");

                    b.Property<string>("LengthLabel")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Protagonist")
                        .HasColumnType("text");

                    b.Property<string>("SortLabel")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("StarRating")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("StoryEra")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EntryTypeId");

                    b.HasIndex("GroupId");

                    b.HasIndex("StatusId");

                    b.ToTable("GameEntries");
                });

            modelBuilder.Entity("CheapNights.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("ThemeColor")
                        .HasColumnType("text");

                    b.Property<string>("ThemePreset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("CheapNights.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("GroupId", "AppUserId")
                        .IsUnique();

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("CheapNights.Models.MemberGamePlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupMemberId")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameEntryId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("GroupMemberId", "GameEntryId")
                        .IsUnique();

                    b.ToTable("MemberGamePlatforms");
                });

            modelBuilder.Entity("CheapNights.Models.NowPlaying", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameEntryId");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("NowPlaying");
                });

            modelBuilder.Entity("CheapNights.Models.PlannedSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomGame")
                        .HasColumnType("text");

                    b.Property<int?>("GameEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("HostMemberId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseCurrentGame")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GameEntryId");

                    b.HasIndex("GroupId");

                    b.HasIndex("HostMemberId");

                    b.ToTable("PlannedSessions");
                });

            modelBuilder.Entity("CheapNights.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Steam",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "PS5",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Plex",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("CheapNights.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChipBackground")
                        .HasColumnType("text");

                    b.Property<string>("ChipColor")
                        .HasColumnType("text");

                    b.Property<bool>("IsSelectable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StripeColor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChipBackground = "rgba(192,57,43,0.1)",
                            ChipColor = "#e05a4a",
                            IsSelectable = true,
                            Name = "Essential",
                            SortOrder = 0,
                            StripeColor = "var(--re-red)"
                        },
                        new
                        {
                            Id = 2,
                            ChipBackground = "rgba(150,150,150,0.08)",
                            ChipColor = "#888",
                            IsSelectable = true,
                            Name = "Recommended",
                            SortOrder = 1,
                            StripeColor = "#888"
                        },
                        new
                        {
                            Id = 3,
                            ChipBackground = "rgba(110,110,110,0.07)",
                            ChipColor = "#666",
                            IsSelectable = true,
                            Name = "Optional",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            ChipColor = "#444",
                            IsSelectable = true,
                            Name = "Skip",
                            SortOrder = 3,
                            StripeColor = "var(--skip-grey)"
                        },
                        new
                        {
                            Id = 5,
                            ChipBackground = "rgba(124,92,191,0.1)",
                            ChipColor = "#a98be8",
                            IsSelectable = true,
                            Name = "Upcoming",
                            SortOrder = 4,
                            StripeColor = "var(--upcoming)"
                        });
                });

            modelBuilder.Entity("CheapNights.Models.Category", b =>
                {
                    b.HasOne("CheapNights.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CheapNights.Models.GameEntry", b =>
                {
                    b.HasOne("CheapNights.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.EntryType", "EntryType")
                        .WithMany()
                        .HasForeignKey("EntryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Category");

                    b.Navigation("EntryType");

                    b.Navigation("Group");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CheapNights.Models.Group", b =>
                {
                    b.HasOne("CheapNights.Models.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CheapNights.Models.GroupMember", b =>
                {
                    b.HasOne("CheapNights.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CheapNights.Models.MemberGamePlatform", b =>
                {
                    b.HasOne("CheapNights.Models.GameEntry", "GameEntry")
                        .WithMany("MemberPlatforms")
                        .HasForeignKey("GameEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.GroupMember", "GroupMember")
                        .WithMany()
                        .HasForeignKey("GroupMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameEntry");

                    b.Navigation("GroupMember");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("CheapNights.Models.NowPlaying", b =>
                {
                    b.HasOne("CheapNights.Models.GameEntry", "GameEntry")
                        .WithMany()
                        .HasForeignKey("GameEntryId");

                    b.HasOne("CheapNights.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameEntry");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CheapNights.Models.PlannedSession", b =>
                {
                    b.HasOne("CheapNights.Models.GameEntry", "GameEntry")
                        .WithMany()
                        .HasForeignKey("GameEntryId");

                    b.HasOne("CheapNights.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.GroupMember", "HostMember")
                        .WithMany()
                        .HasForeignKey("HostMemberId");

                    b.Navigation("GameEntry");

                    b.Navigation("Group");

                    b.Navigation("HostMember");
                });

            modelBuilder.Entity("CheapNights.Models.GameEntry", b =>
                {
                    b.Navigation("MemberPlatforms");
                });

            modelBuilder.Entity("CheapNights.Models.Group", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
