// <auto-generated />
using System;
using CheapNights.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CheapNights.Migrations
{
    [DbContext(typeof(CheapNightsDbContext))]
    partial class CheapNightsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CheapNights.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlexUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Brecht",
                            PlexUserId = "brecht"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Pieter",
                            PlexUserId = "pieter"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Miel",
                            PlexUserId = "miel"
                        });
                });

            modelBuilder.Entity("CheapNights.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeColor")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeColor = "re",
                            Code = "RE",
                            GroupId = 1,
                            Name = "Resident Evil",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            BadgeColor = "sh",
                            Code = "SH",
                            GroupId = 1,
                            Name = "Silent Hill",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            BadgeColor = "s1",
                            Code = "S1",
                            GroupId = 2,
                            Name = "Schedule 1",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("CheapNights.Models.EntryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EntryTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Game",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movie",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "DLC",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("CheapNights.Models.GameEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedTime")
                        .HasColumnType("text");

                    b.Property<int>("EntryTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("GameNote")
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCouchCoop")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMovie")
                        .HasColumnType("boolean");

                    b.Property<string>("LengthLabel")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Protagonist")
                        .HasColumnType("text");

                    b.Property<string>("SortLabel")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("StarRating")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("StoryEra")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EntryTypeId");

                    b.HasIndex("GroupId");

                    b.HasIndex("StatusId");

                    b.ToTable("GameEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Grace & Leon face a new Megamycete threat — series finale, wraps up the Winters saga",
                            GroupId = 1,
                            IsCompleted = true,
                            IsCouchCoop = false,
                            IsMovie = false,
                            LengthLabel = "15h",
                            Name = "RE9 REQUIEM",
                            Protagonist = "Grace + Leon",
                            SortLabel = "✓",
                            SortOrder = 0,
                            StarRating = 3,
                            StatusId = 1,
                            StoryEra = "2026"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Ethan searches for Mia in the Baker estate — first-person horror, soft reboot of the series",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            LengthLabel = "9h",
                            Name = "RE7 BIOHAZARD",
                            Protagonist = "Ethan Winters",
                            SortLabel = "1",
                            SortOrder = 1,
                            StarRating = 2,
                            StatusId = 1,
                            StoryEra = "2017"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Play immediately after RE7 — direct sequel",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            LengthLabel = "10h",
                            Name = "RE8 VILLAGE",
                            Protagonist = "Ethan Winters",
                            SortLabel = "2",
                            SortOrder = 2,
                            StarRating = 2,
                            StatusId = 1,
                            StoryEra = "2021"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            EntryTypeId = 2,
                            GameNote = "Leon, Chris, Jill, Claire & Rebecca reunite — set after Village",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = true,
                            LengthLabel = "1.5h",
                            Name = "RE: DEATH ISLAND (2023)",
                            Protagonist = "Animated (CG)",
                            SortOrder = 3,
                            StarRating = 1,
                            StatusId = 2,
                            StoryEra = "2015"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Closes the Wesker arc",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = true,
                            IsMovie = false,
                            LengthLabel = "12h",
                            Name = "RE5",
                            Protagonist = "Chris + Sheva",
                            SortLabel = "3",
                            SortOrder = 4,
                            StarRating = 2,
                            StatusId = 1,
                            StoryEra = "2009"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            EntryTypeId = 2,
                            GameNote = "Leon in a bio-war zone — bridges RE5 and RE6",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = true,
                            LengthLabel = "1.5h",
                            Name = "RE: DAMNATION (2012)",
                            Protagonist = "Animated (CG)",
                            SortOrder = 5,
                            StarRating = 1,
                            StatusId = 2,
                            StoryEra = "2011"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            EntryTypeId = 2,
                            GameNote = "Leon + Chris + Rebecca, set after RE6 — watch after RE6 recap",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = true,
                            LengthLabel = "1.5h",
                            Name = "RE: VENDETTA (2017)",
                            Protagonist = "Animated (CG)",
                            SortOrder = 6,
                            StarRating = 1,
                            StatusId = 2,
                            StoryEra = "2014"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Jill + Chris on a cruise ship — fills the RE5→RE4 gap",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            LengthLabel = "12h",
                            Name = "RE: REVELATIONS",
                            Protagonist = "Jill Valentine",
                            SortLabel = "3b",
                            SortOrder = 7,
                            StarRating = 2,
                            StatusId = 2,
                            StoryEra = "2005"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Leon at his best",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            LengthLabel = "16h",
                            Name = "RE4 REMAKE",
                            Protagonist = "Leon S. Kennedy",
                            SortLabel = "4",
                            SortOrder = 8,
                            StarRating = 3,
                            StatusId = 1,
                            StoryEra = "2004"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            EntryTypeId = 3,
                            GameNote = "Ada Wong's parallel story — recontextualizes RE4R. Play immediately after.",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            LengthLabel = "6h",
                            Name = "RE4R: SEPARATE WAYS",
                            Protagonist = "Ada Wong",
                            SortLabel = "4+",
                            SortOrder = 9,
                            StarRating = 1,
                            StatusId = 1,
                            StoryEra = "2004"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            EntryTypeId = 2,
                            GameNote = "Leon + Claire reunite ~1yr after RE4",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = true,
                            LengthLabel = "1.5h",
                            Name = "RE: DEGENERATION (2008)",
                            Protagonist = "Animated (CG)",
                            SortOrder = 10,
                            StarRating = 1,
                            StatusId = 2,
                            StoryEra = "2005"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            EntryTypeId = 2,
                            GameNote = "Netflix CG series — Leon & Claire, White House conspiracy",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = true,
                            LengthLabel = "2h",
                            Name = "RE: INFINITE DARKNESS (2021)",
                            Protagonist = "Netflix (CG)",
                            SortOrder = 11,
                            StarRating = 1,
                            StatusId = 2,
                            StoryEra = "2006"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Claire + Barry, prison camp horror — has co-op!",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = true,
                            IsMovie = false,
                            LengthLabel = "12h",
                            Name = "RE: REVELATIONS 2",
                            Protagonist = "Claire + Barry",
                            SortLabel = "5b",
                            SortOrder = 12,
                            StarRating = 2,
                            StatusId = 2,
                            StoryEra = "2011"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Raccoon City's final days",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            LengthLabel = "6h",
                            Name = "RE3 REMAKE",
                            Protagonist = "Jill Valentine",
                            SortLabel = "5",
                            SortOrder = 13,
                            StarRating = 1,
                            StatusId = 2,
                            StoryEra = "1998"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Leon's origin. Where it all began for him.",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            LengthLabel = "8h",
                            Name = "RE2 REMAKE",
                            Protagonist = "Leon + Claire",
                            SortLabel = "6",
                            SortOrder = 14,
                            StarRating = 2,
                            StatusId = 1,
                            StoryEra = "1998"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Watch a story recap instead",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            LengthLabel = "21h",
                            Name = "RE6",
                            Protagonist = "Leon / Chris / Jake",
                            SortLabel = "—",
                            SortOrder = 15,
                            StarRating = 3,
                            StatusId = 4,
                            StoryEra = "2013"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Non-canon multiplayer, dead servers",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            Name = "RE RESISTANCE",
                            Protagonist = "Various",
                            SortLabel = "—",
                            SortOrder = 16,
                            StarRating = 0,
                            StatusId = 4,
                            StoryEra = ""
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Rumored 2027 — Claire's story",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            Name = "CODE VERONICA REMAKE",
                            Protagonist = "Claire Redfield",
                            SortLabel = "🔜",
                            SortOrder = 17,
                            StarRating = 0,
                            StatusId = 5,
                            StoryEra = "2000"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            EntryTypeId = 2,
                            GameNote = "Dir. Zach Cregger (Barbarian)",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = true,
                            LengthLabel = "2h",
                            Name = "RESIDENT EVIL (2026)",
                            Protagonist = "Live-action reboot",
                            SortLabel = "🔜",
                            SortOrder = 18,
                            StarRating = 2,
                            StatusId = 5,
                            StoryEra = "2026"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            EntryTypeId = 1,
                            GameNote = "Early dev — 4–7 years out",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            Name = "RE1 REMAKE",
                            Protagonist = "Chris / Jill",
                            SortLabel = "🔜",
                            SortOrder = 19,
                            StarRating = 0,
                            StatusId = 5,
                            StoryEra = "1998"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            EntryTypeId = 1,
                            GameNote = "FREE on PS5 — standalone intro to Silent Hill themes, modern setting with a new protagonist",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            LengthLabel = "2h",
                            Name = "SH: THE SHORT MESSAGE",
                            Protagonist = "New protagonist",
                            SortLabel = "0",
                            SortOrder = 100,
                            StarRating = 1,
                            StatusId = 1,
                            StoryEra = "2024"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            EntryTypeId = 1,
                            GameNote = "James Sunderland returns to Silent Hill after receiving a letter from his dead wife — psychological horror masterpiece",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            LengthLabel = "10h",
                            Name = "SILENT HILL 2 REMAKE",
                            Protagonist = "Psychological grief horror",
                            SortLabel = "1",
                            SortOrder = 101,
                            StarRating = 2,
                            StatusId = 1,
                            StoryEra = "2024"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            EntryTypeId = 2,
                            GameNote = "Live-action adaptation of SH2 — directed by Christophe Gans, compare with the game version",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = true,
                            LengthLabel = "2h",
                            Name = "RETURN TO SILENT HILL (2026)",
                            Protagonist = "Live-action",
                            SortOrder = 102,
                            StarRating = 2,
                            StatusId = 2,
                            StoryEra = "2026"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            EntryTypeId = 2,
                            GameNote = "Own continuity loosely adapting SH1 + SH3 — not canon to games, optional horror movie night",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = true,
                            LengthLabel = "4h",
                            Name = "SILENT HILL (2006) + REVELATION (2012)",
                            Protagonist = "Live-action duo",
                            SortOrder = 103,
                            StarRating = 2,
                            StatusId = 3,
                            StoryEra = "2006"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            EntryTypeId = 1,
                            GameNote = "Set in 1960s Japan with a completely new story — bold departure from Americana fog, kowloon-style horror",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            LengthLabel = "15h",
                            Name = "SILENT HILL f",
                            Protagonist = "1960s Japan, new setting",
                            SortLabel = "2",
                            SortOrder = 104,
                            StarRating = 3,
                            StatusId = 1,
                            StoryEra = "2025"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            EntryTypeId = 1,
                            GameNote = "Alex Shepherd returns to Shepherd's Glen — combat-focused, Western-developed, widely considered weakest entry",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            Name = "SH HOMECOMING",
                            Protagonist = "Action-heavy, less atmospheric",
                            SortLabel = "—",
                            SortOrder = 105,
                            StarRating = 0,
                            StatusId = 4,
                            StoryEra = "2008"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            EntryTypeId = 1,
                            GameNote = "By No Code (Stories Untold) — Scotland 1996, first-person, P.T.-inspired indie horror set in the SH universe",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            Name = "SH: TOWNFALL",
                            Protagonist = "PT-inspired indie horror",
                            SortLabel = "🔜",
                            SortOrder = 106,
                            StarRating = 0,
                            StatusId = 5,
                            StoryEra = "2026"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            EntryTypeId = 1,
                            GameNote = "Bloober Team remaking the original — Harry Mason searching for his daughter Cheryl, the story that started it all",
                            GroupId = 1,
                            IsCompleted = false,
                            IsCouchCoop = false,
                            IsMovie = false,
                            Name = "SH1 REMAKE",
                            Protagonist = "Original Spencer Mansion",
                            SortLabel = "🔜",
                            SortOrder = 107,
                            StarRating = 0,
                            StatusId = 5,
                            StoryEra = "2027"
                        });
                });

            modelBuilder.Entity("CheapNights.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThemeColor")
                        .HasColumnType("text");

                    b.Property<string>("ThemePreset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Survival horror roadmap — Resident Evil & Silent Hill",
                            IconName = "Theaters",
                            Name = "Horror Nights",
                            ThemeColor = "#c0392b",
                            ThemePreset = "horror-dark"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Schedule 1 gaming sessions",
                            IconName = "SportsEsports",
                            Name = "Schedule 1",
                            ThemeColor = "#4caf50",
                            ThemePreset = "forest"
                        });
                });

            modelBuilder.Entity("CheapNights.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("GroupId", "AppUserId")
                        .IsUnique();

                    b.ToTable("GroupMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 1,
                            GroupId = 1,
                            Nickname = "brecht"
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = 2,
                            GroupId = 1,
                            Nickname = "pieter"
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = 1,
                            GroupId = 2,
                            Nickname = "brecht"
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = 3,
                            GroupId = 2,
                            Nickname = "miel"
                        });
                });

            modelBuilder.Entity("CheapNights.Models.MemberGamePlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupMemberId")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameEntryId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("GroupMemberId", "GameEntryId")
                        .IsUnique();

                    b.ToTable("MemberGamePlatforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameEntryId = 5,
                            GroupMemberId = 1,
                            PlatformId = 1
                        },
                        new
                        {
                            Id = 2,
                            GameEntryId = 14,
                            GroupMemberId = 1,
                            PlatformId = 1
                        },
                        new
                        {
                            Id = 3,
                            GameEntryId = 17,
                            GroupMemberId = 1,
                            PlatformId = 1
                        },
                        new
                        {
                            Id = 4,
                            GameEntryId = 23,
                            GroupMemberId = 1,
                            PlatformId = 3
                        },
                        new
                        {
                            Id = 5,
                            GameEntryId = 1,
                            GroupMemberId = 2,
                            PlatformId = 2
                        },
                        new
                        {
                            Id = 6,
                            GameEntryId = 2,
                            GroupMemberId = 2,
                            PlatformId = 2
                        },
                        new
                        {
                            Id = 7,
                            GameEntryId = 3,
                            GroupMemberId = 2,
                            PlatformId = 2
                        },
                        new
                        {
                            Id = 8,
                            GameEntryId = 21,
                            GroupMemberId = 2,
                            PlatformId = 2
                        });
                });

            modelBuilder.Entity("CheapNights.Models.NowPlaying", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameEntryId");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("NowPlaying");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameEntryId = 1,
                            GroupId = 1,
                            StatusNote = "almost finished, Arc reached",
                            UpdatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            GroupId = 2,
                            UpdatedAt = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CheapNights.Models.PlannedSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomGame")
                        .HasColumnType("text");

                    b.Property<int?>("GameEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("HostMemberId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseCurrentGame")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GameEntryId");

                    b.HasIndex("GroupId");

                    b.HasIndex("HostMemberId");

                    b.ToTable("PlannedSessions");
                });

            modelBuilder.Entity("CheapNights.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Steam",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "PS5",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Plex",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("CheapNights.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChipBackground")
                        .HasColumnType("text");

                    b.Property<string>("ChipColor")
                        .HasColumnType("text");

                    b.Property<bool>("IsSelectable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StripeColor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChipBackground = "rgba(192,57,43,0.1)",
                            ChipColor = "#e05a4a",
                            IsSelectable = true,
                            Name = "Essential",
                            SortOrder = 0,
                            StripeColor = "var(--re-red)"
                        },
                        new
                        {
                            Id = 2,
                            ChipBackground = "rgba(150,150,150,0.08)",
                            ChipColor = "#888",
                            IsSelectable = true,
                            Name = "Recommended",
                            SortOrder = 1,
                            StripeColor = "#888"
                        },
                        new
                        {
                            Id = 3,
                            ChipBackground = "rgba(110,110,110,0.07)",
                            ChipColor = "#666",
                            IsSelectable = true,
                            Name = "Optional",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            ChipColor = "#444",
                            IsSelectable = true,
                            Name = "Skip",
                            SortOrder = 3,
                            StripeColor = "var(--skip-grey)"
                        },
                        new
                        {
                            Id = 5,
                            ChipBackground = "rgba(124,92,191,0.1)",
                            ChipColor = "#a98be8",
                            IsSelectable = true,
                            Name = "Upcoming",
                            SortOrder = 4,
                            StripeColor = "var(--upcoming)"
                        });
                });

            modelBuilder.Entity("CheapNights.Models.Category", b =>
                {
                    b.HasOne("CheapNights.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CheapNights.Models.GameEntry", b =>
                {
                    b.HasOne("CheapNights.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.EntryType", "EntryType")
                        .WithMany()
                        .HasForeignKey("EntryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Category");

                    b.Navigation("EntryType");

                    b.Navigation("Group");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CheapNights.Models.GroupMember", b =>
                {
                    b.HasOne("CheapNights.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CheapNights.Models.MemberGamePlatform", b =>
                {
                    b.HasOne("CheapNights.Models.GameEntry", "GameEntry")
                        .WithMany("MemberPlatforms")
                        .HasForeignKey("GameEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.GroupMember", "GroupMember")
                        .WithMany()
                        .HasForeignKey("GroupMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameEntry");

                    b.Navigation("GroupMember");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("CheapNights.Models.NowPlaying", b =>
                {
                    b.HasOne("CheapNights.Models.GameEntry", "GameEntry")
                        .WithMany()
                        .HasForeignKey("GameEntryId");

                    b.HasOne("CheapNights.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameEntry");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CheapNights.Models.PlannedSession", b =>
                {
                    b.HasOne("CheapNights.Models.GameEntry", "GameEntry")
                        .WithMany()
                        .HasForeignKey("GameEntryId");

                    b.HasOne("CheapNights.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheapNights.Models.GroupMember", "HostMember")
                        .WithMany()
                        .HasForeignKey("HostMemberId");

                    b.Navigation("GameEntry");

                    b.Navigation("Group");

                    b.Navigation("HostMember");
                });

            modelBuilder.Entity("CheapNights.Models.GameEntry", b =>
                {
                    b.Navigation("MemberPlatforms");
                });

            modelBuilder.Entity("CheapNights.Models.Group", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
